languages: node_js
node_js:
  - node
branches:
  only:
    - master
before_install:
    # https://github.com/containers/libpod/blob/master/install.md#ubuntu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
  - podman --version
  - podman version
  - podman info --debug
  - apt-cache show podman
  - dpkg-query -L podman
  - ls -1 /etc/containers/registries.conf || true
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
script:
  - ./install.sh
